const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let total=3000,left=3000,timerId=null,paused=false,finishedTime='刚刚';
const state={task:'写完第 12 章',goal:'完成至少 2000 字初稿',result:'完成第 12 章初稿，共 2,371 字'};
function show(name){$$('.page').forEach(p=>p.classList.toggle('on',p.dataset.page===name));history.replaceState(null,'',`?screen=${name}`)}
function sync(){state.task=$('#task').value.trim()||'完成一件重要的事';state.goal=$('#goal').value.trim()||'得到一个明确成果';state.result=$('#result').value.trim()||'完成了这次成果';$('#focusTask').textContent=state.task;$('#focusGoal').textContent=state.goal;$('#resultTask').textContent=state.task;$('#resultGoal').textContent=state.goal;$('#rewardStory').textContent=`它记住了「${state.task}」。以后看到这盏灯，你看到的不是一段计时，而是那一次真实完成。`;$('#receiptText').textContent=state.result;$('#archiveResult').textContent=state.result;$('#sheetResult').textContent=state.result;$('#sheetTask').textContent=state.task}
function durationText(){return total<60?`${total} 秒演示`:`${Math.round(total/60)} 分钟`}
$$('.duration').forEach(b=>b.onclick=()=>{$$('.duration').forEach(x=>x.classList.remove('on'));b.classList.add('on');total=+b.dataset.sec});
$('#start').onclick=()=>{if(!$('#task').value.trim()||!$('#goal').value.trim())return;sync();left=total;paused=false;show('focus');render();clearInterval(timerId);timerId=setInterval(()=>{if(!paused){left--;render();if(left<=0)finish()}},1000)};
function render(){const p=Math.max(0,Math.min(1,1-left/total)),pct=Math.round(p*100);$('#timer').textContent=left<60?`00:${String(left).padStart(2,'0')}`:`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;$('#focusStep').textContent=`02 / FOCUS · ${pct}%`;$('#bar').style.width=pct+'%';const sc=$('#focusScene');sc.classList.remove('s2','s3','s4');if(p>.75)sc.classList.add('s4');else if(p>.5)sc.classList.add('s3');else if(p>.25)sc.classList.add('s2');$('#stageCopy').textContent=p<.25?'正在打底':p<.5?'轮廓出现了':p<.75?'开始有了温度':'快要完成了'}
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'继续':'暂停';$('#focusScene').classList.toggle('paused',paused);$('#sceneStatus').textContent=paused?'工坊暂停了':'工坊正在工作';$('#focusHint').textContent=paused?'时间停住了':'现实里的事才是主线'};
function finish(){clearInterval(timerId);const d=new Date();finishedTime=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;sync();show('result')}
$('#done').onclick=finish;$('#result').oninput=()=>{state.result=$('#result').value};
$('#claim').onclick=()=>{if(!$('#result').value.trim())return;sync();show('reveal');$('#sealWrap').style.display='block';$('#rewardContent').classList.remove('on');$('#revealBottom').hidden=true;setTimeout(()=>{try{const AudioContext=window.AudioContext||window.webkitAudioContext;const ctx=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(660,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(880,ctx.currentTime+.12);g.gain.setValueAtTime(.04,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.28);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.28)}catch(e){}$('#sealWrap').style.display='none';$('#rewardContent').classList.add('on');$('#revealBottom').hidden=false;makeRays();confetti()},760)};
function makeRays(){const art=$('#rewardArt');art.querySelectorAll('.ray').forEach(x=>x.remove());for(let i=0;i<12;i++){const r=document.createElement('i');r.className='ray';r.style.transform=`rotate(${i*30}deg)`;art.prepend(r)}}
function confetti(){const host=document.querySelector('.reveal');const colors=['#d37152','#d4a552','#445a4a','#b89e77','#e7d3a8'];for(let i=0;i<26;i++){const e=document.createElement('i');e.className='confetti';e.style.left=(i*37%100)+'%';e.style.top=(-70-(i%8)*18)+'px';e.style.background=colors[i%colors.length];e.style.setProperty('--drift',((i*17)%56-28)+'px');e.style.animationDelay=((i%9)*.05)+'s';host.appendChild(e);setTimeout(()=>e.remove(),2000)}}
$('#place').onclick=()=>{sync();$('#archiveMeta').textContent=`${state.task} · ${durationText()} · ${finishedTime}`;$('#sheetDuration').textContent=durationText();$('#sheetTime').textContent=finishedTime;show('room')};
function openSheet(){sync();$('#sheetDuration').textContent=durationText();$('#sheetTime').textContent=finishedTime;$('#sheetBackdrop').classList.add('on')}
$('#lampTap').onclick=openSheet;$('#collectionLamp').onclick=openSheet;$('#archive').onclick=openSheet;$('#closeSheet').onclick=()=>$('#sheetBackdrop').classList.remove('on');$('#sheetBackdrop').onclick=e=>{if(e.target===$('#sheetBackdrop'))$('#sheetBackdrop').classList.remove('on')};$('#again').onclick=()=>show('setup');
const qs=new URLSearchParams(location.search),requested=qs.get('screen');if(requested&&['setup','focus','result','reveal','room'].includes(requested)){sync();if(requested==='focus'){total=3000;left=1110;render()}if(requested==='reveal'){show('reveal');$('#sealWrap').style.display='none';$('#rewardContent').classList.add('on');$('#revealBottom').hidden=false;makeRays()}else show(requested)}
