(() => {
  const accent='#4b715a', accentStrong='#355342';
  const style=document.createElement('style');
  style.textContent=`
  :root{--accent:${accent};--accent2:${accentStrong};--bg:#f4f6f3;--surface:#fff;--line:#e7ebe7;--text:#151716;--text2:#626762;--text3:#9aa09a;--danger:#dc6262;--success:#5f8a6a;--serif:"Songti SC","STSong","Noto Serif CJK SC",serif;--ui:-apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC",Arial,sans-serif}
  *{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:var(--ui);color:var(--text);background:radial-gradient(circle at 18% 8%,#fff 0 18%,transparent 42%),linear-gradient(135deg,#edf0ed,#fafbf8 48%,#edf1ed);-webkit-font-smoothing:antialiased}button,input,textarea{font:inherit}button{border:0;background:none;color:inherit;padding:0;cursor:pointer}svg{display:block}
  #app{min-height:100vh;display:grid;grid-template-columns:220px 393px 220px;gap:34px;align-items:center;justify-content:center;padding:28px}.side h1{font:48px/1 var(--serif);letter-spacing:.08em;margin:0 0 14px}.brandline{width:42px;height:3px;border-radius:9px;background:var(--accent);margin-bottom:28px}.slogan{font:22px/1.75 var(--serif);letter-spacing:.04em}.aside{margin-top:48px;color:#a7aaa6;font:14px/2.2 var(--serif);letter-spacing:.15em}
  .phone{position:relative;width:393px;height:852px;background:#000;border-radius:54px;padding:8px;box-shadow:0 28px 90px rgba(19,29,24,.16),0 8px 28px rgba(19,29,24,.08),0 0 0 1px rgba(0,0,0,.25);overflow:hidden}.phone:before{content:"";position:absolute;inset:2px;border-radius:52px;border:1px solid rgba(255,255,255,.18);pointer-events:none;z-index:99}.viewport{position:relative;width:100%;height:100%;overflow:hidden;background:var(--bg);border-radius:46px}.island{position:absolute;top:11px;left:50%;transform:translateX(-50%);width:116px;height:31px;border-radius:20px;background:#050505;z-index:60}.screen{position:absolute;inset:0;background:var(--bg);overflow:hidden}.status{position:absolute;top:0;left:0;right:0;height:49px;padding:12px 20px 0;display:flex;justify-content:space-between;font-size:11px;font-weight:700;z-index:70;pointer-events:none}.status.light{color:white}.status-icons{display:flex;gap:5px;align-items:center}.battery{width:19px;height:9px;border:1.5px solid currentColor;border-radius:2px;position:relative}.battery:after{content:"";position:absolute;right:-3px;top:2px;width:2px;height:4px;border-radius:1px;background:currentColor}.battery:before{content:"";position:absolute;inset:1px 2px;background:currentColor;border-radius:1px}
  .head{height:96px;padding:54px 18px 12px;display:flex;align-items:center;justify-content:space-between;background:rgba(255,255,255,.96);border-bottom:1px solid rgba(0,0,0,.025);backdrop-filter:blur(18px)}.head h2{margin:0;font-size:21px;font-weight:760}.iconbtn{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;color:var(--text2)}.iconbtn svg{width:21px;height:21px}.body{height:calc(100% - 96px);overflow:auto;padding:16px 16px 106px;scrollbar-width:none}.body::-webkit-scrollbar,.feed::-webkit-scrollbar{display:none}.card{background:white;border-radius:22px;box-shadow:0 12px 26px rgba(28,38,31,.055);border:1px solid rgba(0,0,0,.02)}
  .tabbar{position:absolute;left:0;right:0;bottom:0;height:82px;padding:8px 10px 12px;display:grid;grid-template-columns:repeat(5,1fr);background:rgba(255,255,255,.97);border-top:1px solid var(--line);z-index:50;backdrop-filter:blur(20px)}.tab{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:12px;color:#8d928d}.tab.active{color:var(--accent2)}.tab svg{width:22px;height:22px;stroke-width:1.9}.plusbox{width:42px;height:42px;border-radius:13px;background:var(--accent2);display:grid;place-items:center;color:#fff;box-shadow:0 8px 18px rgba(53,83,66,.18)}
  .feed{height:calc(100% - 82px);overflow-y:auto;scroll-snap-type:y mandatory;scrollbar-width:none}.feeditem{position:relative;height:100%;scroll-snap-align:start;background-size:cover;background-position:center}.feeditem:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.16),rgba(0,0,0,.04) 30%,rgba(0,0,0,.12) 58%,rgba(0,0,0,.62) 100%)}.feedtop{position:absolute;top:50px;left:0;right:0;height:52px;display:flex;justify-content:center;gap:30px;align-items:center;z-index:6;color:rgba(255,255,255,.72);font-size:18px;font-weight:700}.feedtop b{color:#fff;position:relative}.feedtop b:after{content:"";position:absolute;left:50%;bottom:-10px;width:34px;height:3px;background:#fff;border-radius:99px;transform:translateX(-50%)}.searchFloat{position:absolute;right:18px;top:63px;z-index:7;color:white}.searchFloat svg{width:22px;height:22px}.quote{position:absolute;left:34px;right:96px;top:168px;z-index:5;color:#fff;font:38px/1.42 var(--serif);letter-spacing:.03em;text-shadow:0 2px 10px rgba(0,0,0,.18)}.author{margin-top:22px;font-size:17px}.meta{position:absolute;left:20px;right:112px;bottom:104px;z-index:5;color:#fff}.chip{display:inline-flex;padding:7px 14px;border-radius:999px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.22);font-size:14px}.desc{margin-top:16px;font-size:17px;line-height:1.55}.rail{position:absolute;right:12px;bottom:98px;z-index:6;display:flex;flex-direction:column;gap:22px}.rail .avatar{width:52px;height:52px;border-radius:50%;overflow:hidden;border:2px solid #fff}.rail .avatar img,.avatar img,.profileAvatar img{width:100%;height:100%;object-fit:cover}.railbtn{display:flex;flex-direction:column;align-items:center;gap:8px;color:#fff;font-size:14px}.railbtn svg{width:29px;height:29px;filter:drop-shadow(0 2px 5px rgba(0,0,0,.24))}
  .searchbox{height:46px;border-radius:14px;background:#f0f2ef;display:flex;align-items:center;gap:10px;padding:0 14px;color:var(--text3);font-size:14px}.searchbox input{border:0;outline:0;background:transparent;flex:1;font-size:14px}.chips{display:flex;gap:9px;flex-wrap:wrap;margin:14px 0 20px}.topic{padding:8px 14px;border-radius:999px;background:#f1f3f0;color:var(--text2);font-size:12px}.topic.active{background:#edf3ee;color:var(--accent2)}.sectionTitle{display:flex;justify-content:space-between;align-items:center;margin:20px 2px 12px;font-size:16px;font-weight:740}.sectionTitle small{font-size:12px;font-weight:500;color:var(--text3)}
  .topics{display:grid;grid-template-columns:1fr 1fr;gap:12px}.topiccard{height:112px;border-radius:18px;overflow:hidden;position:relative;color:#fff;padding:14px;background-size:cover;background-position:center}.topiccard:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.04),rgba(0,0,0,.55))}.topiccard strong,.topiccard span{position:relative;z-index:1}.topiccard strong{display:block;margin-top:46px;font:17px/1.35 var(--serif)}.topiccard span{font-size:11px}.list{overflow:hidden}.row{display:grid;grid-template-columns:44px 1fr auto;gap:12px;align-items:center;padding:13px 14px;border-bottom:1px solid var(--line)}.row:last-child{border-bottom:0}.avatar{width:44px;height:44px;border-radius:50%;overflow:hidden;background:#e7eae6}.row strong{font-size:13px}.row p{margin:4px 0 0;color:var(--text3);font-size:10px;line-height:1.45}.pill{padding:8px 12px;border-radius:999px;background:#f2f4f1;color:var(--text2);font-size:11px}
  .detailHero{margin:8px 16px 0;border-radius:24px;overflow:hidden;background:white;box-shadow:0 14px 28px rgba(28,38,31,.06)}.heroImg{height:260px;background-size:cover;background-position:center;position:relative}.heroImg:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(255,255,255,.18),rgba(255,255,255,.05) 38%,rgba(0,0,0,.18))}.heroQuote{position:absolute;left:28px;right:28px;top:56px;z-index:1;text-align:center;font:30px/1.48 var(--serif)}.heroQuote small{display:block;margin-top:10px;font:15px var(--ui);color:#555}.statsline{display:flex;gap:20px;padding:14px;color:var(--text2);font-size:12px}.statsline span{display:flex;align-items:center;gap:5px}.statsline svg{width:19px;height:19px}.comments{margin:12px 16px 90px;padding:0 14px}.commentTitle{height:48px;display:flex;align-items:center;justify-content:space-between;font-size:14px;font-weight:740;border-bottom:1px solid var(--line)}.comment{display:grid;grid-template-columns:38px 1fr auto;gap:10px;padding:14px 0;border-bottom:1px solid var(--line)}.comment:last-child{border-bottom:0}.comment .avatar{width:38px;height:38px}.comment p{margin:4px 0;color:var(--text2);font-size:12px;line-height:1.6}.comment small{font-size:10px;color:var(--text3)}.inputbar{position:absolute;left:0;right:0;bottom:0;height:74px;padding:10px 12px;background:rgba(255,255,255,.98);border-top:1px solid var(--line);display:flex;gap:8px}.inputpill{flex:1;height:42px;border-radius:999px;background:#f2f4f1;padding:0 15px;display:flex;align-items:center;color:var(--text3);font-size:13px}.send{width:42px;height:42px;border-radius:50%;background:var(--accent);color:#fff;display:grid;place-items:center}
  .composer{padding:16px}.composer textarea{width:100%;height:150px;resize:none;border:0;outline:0;background:transparent;font:18px/1.8 var(--serif)}.counter{text-align:right;color:var(--text3);font-size:11px}.field{margin-top:14px;padding:13px 14px;border-radius:16px;background:#f7f8f6;display:flex;gap:10px;font-size:13px}.field label{width:72px;color:var(--text3)}.field input{flex:1;border:0;outline:0;background:transparent}.preview{overflow:hidden}.previewImg{height:120px;background-size:cover;background-position:center}.previewCopy{padding:18px}.previewCopy strong{font:25px/1.55 var(--serif)}.previewCopy span{display:block;margin-top:12px;color:var(--text2);font:15px var(--serif)}.cta{height:42px;padding:0 18px;border-radius:999px;background:var(--accent);color:#fff;font-size:14px;font-weight:600}.cta.alt{background:#fff;color:var(--text);border:1px solid var(--line)}.result{height:100%;display:flex;flex-direction:column;justify-content:center;align-items:center;padding:0 24px 100px;text-align:center}.resultIcon{width:88px;height:88px;border-radius:50%;display:grid;place-items:center;margin-bottom:24px}.resultIcon.ok{background:#edf6ef;color:var(--success)}.resultIcon.fail{background:#fff0f0;color:var(--danger)}.resultIcon svg{width:42px;height:42px}.result h2{font-size:28px;margin:0}.result p{color:var(--text2);font-size:14px;line-height:1.7}.resultActions{width:100%;max-width:300px;display:flex;flex-direction:column;gap:10px;margin-top:18px}.resultActions .cta{width:100%}
  .profileTop{padding:72px 18px 18px;background:#fff}.profileHead{display:grid;grid-template-columns:72px 1fr auto;gap:14px;align-items:center}.profileAvatar{width:72px;height:72px;border-radius:50%;overflow:hidden}.profileName{font-size:26px;font-weight:780}.bio{margin-top:6px;color:var(--text2);font-size:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);margin-top:22px;text-align:center}.stats strong{display:block;font-size:24px}.stats span{display:block;margin-top:8px;color:var(--text3);font-size:13px}.profileBody{padding:16px}.menurow{display:grid;grid-template-columns:26px 1fr auto;gap:12px;align-items:center;padding:18px;border-bottom:1px solid var(--line);font-size:14px;font-weight:700}.menurow:last-child{border-bottom:0}.menurow small{color:var(--text3);font-weight:500}.saved{display:grid;grid-template-columns:72px 1fr auto;gap:12px;padding:14px;border-bottom:1px solid var(--line)}.saved:last-child{border-bottom:0}.thumb{height:72px;border-radius:14px;background-size:cover;background-position:center}.saved strong{font:16px/1.55 var(--serif)}.saved small{display:block;margin-top:8px;color:var(--text3);font-size:11px}.formCard{padding:16px}.formAvatar{display:flex;justify-content:center;margin-bottom:18px}.formAvatar .profileAvatar{width:88px;height:88px}.inputGroup{margin-bottom:14px}.inputGroup label{display:block;margin-bottom:8px;color:var(--text3);font-size:12px}.inputShell{min-height:48px;padding:0 14px;border-radius:16px;background:#f7f8f6;display:flex;align-items:center;font-size:14px}.inputShell.multi{min-height:92px;align-items:flex-start;padding-top:14px;line-height:1.7}.settingrow{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center;padding:16px 18px;border-bottom:1px solid var(--line);font-size:14px}.settingrow:last-child{border-bottom:0}.settingrow .label{display:flex;gap:12px;align-items:center}.settingrow .label svg{width:18px;height:18px;color:var(--text3)}
  .index{padding:14px;background:rgba(255,255,255,.75);border:1px solid rgba(255,255,255,.92);border-radius:22px;box-shadow:0 14px 40px rgba(31,42,34,.07)}.index h3{font-size:12px;color:var(--text3);margin:4px 8px 10px}.index button{width:100%;padding:9px 10px;border-radius:12px;text-align:left;font-size:12px;color:var(--text2)}.index button.active,.index button:hover{background:#f1f4f1;color:var(--accent2)}.token{margin-top:14px;padding:16px;background:rgba(255,255,255,.6);border-radius:20px;font-size:11px;line-height:1.7;color:var(--text3)}
  @media(max-width:980px){#app{padding:0;display:block}.side,.right{display:none}.phone{width:100vw;height:100dvh;border-radius:0;padding:0;box-shadow:none}.phone:before,.island{display:none}.viewport{border-radius:0}}
  `;
  document.head.appendChild(style);

  const icon=(name)=>({home:'<path d="M4 11.5 12 5l8 6.5V20H4z"/>',discover:'<circle cx="12" cy="12" r="8"/><path d="M8.2 15.8 15.8 8.2"/>',plus:'<path d="M12 5v14M5 12h14"/>',msg:'<path d="M21 15a3 3 0 0 1-3 3H8l-5 4V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3Z"/>',user:'<path d="M19 21a7 7 0 0 0-14 0"/><circle cx="12" cy="8" r="4"/>',back:'<path d="m15 18-6-6 6-6"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',heart:'<path d="M12 21s-7-4.4-7-10.5A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 7 3.5C19 16.6 12 21 12 21Z"/>',star:'<path d="m12 3 2.6 5.3 5.8.8-4.2 4.1 1 5.8L12 16.9 6.8 19l1-5.8L3.6 9.1l5.8-.8Z"/>',share:'<path d="M7 17 17 7"/><path d="M7 7h10v10"/>',check:'<path d="m5 12 5 5L20 7"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6"/><path d="M12 16h.01"/>'}[name]||'');
  const svg=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor">${icon(name)}</svg>`;
  const status=(light=false)=>`<div class="status ${light?'light':''}"><span>9:41</span><div class="status-icons"><span>●</span><span>●</span><span>⌁</span><span class="battery"></span></div></div>`;
  const head=(title,right='')=>`<div class="head"><button class="iconbtn" data-back>${svg('back')}</button><h2>${title}</h2>${right||'<div style="width:36px"></div>'}</div>`;
  const tabbar=(active)=>`<nav class="tabbar">${[['home-reco','home','首页'],['discover','discover','发现'],['publish','plus','发布'],['messages','msg','消息'],['profile','user','我的']].map(([p,i,t])=>`<button class="tab ${active===p?'active':''}" data-nav="${p}">${p==='publish'?`<span class="plusbox">${svg(i)}</span>`:svg(i)}<span>${t}</span></button>`).join('')}</nav>`;
  const pic={mountain:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',forest:'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80',sea:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',person:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',woman:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80'};
  const avatar=(src=pic.person)=>`<div class="avatar"><img src="${src}"></div>`;
  const rail=()=>`<div class="rail"><div class="avatar"><img src="${pic.person}"></div><button class="railbtn">${svg('heart')}<span>1.2万</span></button><button class="railbtn" data-nav="detail">${svg('msg')}<span>642</span></button><button class="railbtn">${svg('star')}<span>3.4万</span></button><button class="railbtn">${svg('share')}<span>分享</span></button></div>`;

  const pages={
    'home-reco':()=>`${status(true)}<div class="feedtop"><b>推荐</b><button data-nav="home-follow">关注</button></div><button class="searchFloat" data-nav="search">${svg('search')}</button><div class="feed"><section class="feeditem" style="background-image:url('${pic.mountain}')"><div class="quote">慢慢来，<br>比较快。<div class="author">—— 叔本华</div></div><div class="meta"><span class="chip"># 生活</span><div class="desc">节奏，比速度更重要。</div></div>${rail()}</section></div>${tabbar('home-reco')}`,
    'home-follow':()=>`${status(true)}<div class="feedtop"><button data-nav="home-reco">推荐</button><b>关注</b></div><button class="searchFloat" data-nav="search">${svg('search')}</button><div class="feed"><section class="feeditem" style="background-image:url('${pic.forest}')"><div class="quote">一个人能走多远，<br>取决于他与什么样的人同行。<div class="author">—— 乔布斯</div></div><div class="meta"><span class="chip"># 成长</span><div class="desc">好的同行，是另一种光。</div></div>${rail()}</section></div>${tabbar('home-reco')}`,
    discover:()=>`${status()}<div class="head"><div></div><h2 style="margin-right:auto">发现</h2><button class="iconbtn" data-nav="search">${svg('search')}</button></div><div class="body"><button class="searchbox" style="width:100%" data-nav="search">${svg('search')}<span>搜索金句、作者或话题</span></button><div class="chips">${['成长','人生','商业','情感','哲学','生活'].map((x,i)=>`<span class="topic ${!i?'active':''}">${x}</span>`).join('')}</div><div class="sectionTitle"><span>热门专题</span><small>查看全部</small></div><div class="topics"><div class="topiccard" style="background-image:url('${pic.sea}')"><span>1.2万人收藏</span><strong>成为更好的自己</strong></div><div class="topiccard" style="background-image:url('${pic.forest}')"><span>8923人收藏</span><strong>在不确定中前行</strong></div></div><div class="sectionTitle"><span>推荐作者</span><small>查看更多</small></div><div class="card list">${[['村上春树','用温柔的文字，抵达内心的远方',pic.person],['杨绛','生活不易，却依然优雅',pic.woman],['尼采','凡不能毁灭我的，使我更强大',pic.person]].map(x=>`<div class="row">${avatar(x[2])}<div><strong>${x[0]}</strong><p>${x[1]}<br>12.4万 人关注</p></div><button class="pill">关注</button></div>`).join('')}</div></div>${tabbar('discover')}`,
    search:()=>`${status()}${head('搜索','<button class="iconbtn" data-back>取消</button>')}<div class="body"><div class="searchbox">${svg('search')}<input value="叔本华"></div><div class="sectionTitle"><span>最近搜索</span><small>清空</small></div><div class="chips"><span class="topic">村上春树</span><span class="topic active">生活</span><span class="topic">成长</span><span class="topic">爱情</span></div><div class="sectionTitle"><span>热门搜索</span></div><div class="card" style="padding:16px;font-size:14px;line-height:2.2"><b style="color:#d96a6a">1</b>　人生的意义<br><b style="color:#d96a6a">2</b>　如何面对不确定<br><b>3</b>　村上春树<br><b>4</b>　成为更好的自己<br><b>5</b>　慢下来</div><div class="sectionTitle"><span>相关结果</span></div><div class="card saved"><div class="thumb" style="background-image:url('${pic.mountain}')"></div><div><strong>世界上只有一种真正的英雄主义，就是在认清生活的真相后依然热爱生活。</strong><small>—— 罗曼·罗兰</small></div><div></div></div></div>`,
    detail:()=>`${status()}${head('')}<div class="detailHero"><div class="heroImg" style="background-image:url('${pic.mountain}')"><div class="heroQuote">慢慢来，<br>比较快。<small>—— 叔本华</small></div></div><div class="statsline"><span>${svg('heart')}1.2万</span><span>${svg('msg')}642</span><span>${svg('star')}3.4万</span><span>${svg('share')}分享</span></div></div><div class="card comments"><div class="commentTitle"><span>全部评论（642）</span><small>最热</small></div>${[['夏天的风','这句话在我焦虑的时候给了我很大的安慰。慢下来，反而能看清真正重要的东西。',pic.woman],['Linen','人生是一场长跑，节奏比速度更重要。',pic.person],['一只猫','简单的四个字，道出了很多人生的真相。',pic.person]].map(x=>`<div class="comment">${avatar(x[2])}<div><strong>${x[0]}</strong><p>${x[1]}</p><small>3月12日　回复</small></div><small>862</small></div>`).join('')}</div><div class="inputbar"><div class="inputpill">写下你的评论…</div><button class="send">${svg('share')}</button></div>`,
    messages:()=>`${status()}<div class="head"><div></div><h2 style="margin-right:auto">消息</h2><div class="pill">互动　通知</div></div><div class="body"><div class="card list">${[['❤','有人喜欢了你的发布','@走在路上 等 3 人赞了你的内容'],['💬','有人评论了你的发布','@Lemon：说得真好！'],['👤','新的关注','@清风、@山月 关注了你'],['@','@ 提到了你','@阿远：很有共鸣'],['✓','系统通知','见字 v2.0 正式上线 🎉']].map((x,i)=>`<button class="row" ${i<2?'data-nav="message-detail"':''}><div class="avatar" style="display:grid;place-items:center;background:${['#f4b9bd','#a4d0a9','#99bee7','#c1a8f3','#c6c8cd'][i]};color:white;font-size:18px">${x[0]}</div><div><strong>${x[1]}</strong><p>${x[2]}</p></div><small style="color:var(--text3)">${i?'2小时前':'1分钟前'}</small></button>`).join('')}</div></div>${tabbar('messages')}`,
    'message-detail':()=>`${status()}${head('互动详情')}<div class="body"><div class="card" style="padding:16px;display:grid;grid-template-columns:1fr 90px;gap:12px"><div><div style="font:20px/1.55 var(--serif)">生活不是等待风暴过去，<br>而是学会在雨中跳舞。</div><div style="margin-top:12px;color:var(--text3);font-size:12px">—— 海明威</div></div><div class="thumb" style="height:90px;background-image:url('${pic.sea}')"></div></div><div class="sectionTitle"><span>全部回复（12）</span></div><div class="card list">${[['是杏杏上号','这句话让我意识到：真正努力不是着急，而是稳稳走好每一步。',pic.woman],['moon','每次刷到这句话，都觉得晚点见太阳都值得。',pic.person]].map(x=>`<div class="row">${avatar(x[2])}<div><strong>${x[0]}</strong><p>${x[1]}</p></div><small>♡ 52</small></div>`).join('')}</div></div>`,
    publish:()=>`${status()}${head('发布','<button class="cta" data-nav="publish-success">发布</button>')}<div class="body"><div class="card composer"><textarea>生活不是等待风暴过去，\n而是学会在雨中跳舞。</textarea><div class="counter">24 / 300</div><div class="field"><label>来源（选填）</label><input value="例如：人间值得"></div><div class="field"><label>作者（选填）</label><input value="例如：中村恒子"></div><div class="chips"><span class="topic active"># 成长</span><span class="topic"># 人生</span><span class="topic"># 情感</span><span class="topic"># 哲学</span></div></div><div class="sectionTitle"><span>预览</span><small>发布后展示效果</small></div><div class="card preview"><div class="previewImg" style="background-image:url('${pic.forest}')"></div><div class="previewCopy"><strong>在黑暗中，<br>也要心怀光明。</strong><span>—— 加西亚·马尔克斯</span></div></div><div style="display:flex;gap:10px;margin-top:14px"><button class="cta" data-nav="publish-success">发布成功</button><button class="cta alt" data-nav="publish-fail">发布失败</button></div></div>`,
    'publish-success':()=>`${status()}<div class="result"><div class="resultIcon ok">${svg('check')}</div><h2>发布成功</h2><p>感谢你分享这份文字，<br>它会被更多人看见。</p><div class="resultActions"><button class="cta" data-nav="home-reco">继续浏览</button><button class="cta alt" data-nav="detail">查看内容</button></div></div>`,
    'publish-fail':()=>`${status()}<div class="result"><div class="resultIcon fail">${svg('alert')}</div><h2>发布失败</h2><p>网络连接异常，请检查网络后重试。</p><div class="resultActions"><button class="cta" data-nav="publish">重试</button><button class="cta alt" data-nav="home-reco">返回首页</button></div></div>`,
    profile:()=>`${status()}<div style="height:calc(100% - 82px);overflow:auto"><div class="profileTop"><div class="profileHead"><div class="profileAvatar"><img src="${pic.person}"></div><div><div class="profileName">晚风</div><div class="bio">在文字中，遇见更大的自己。</div></div><button class="pill" data-nav="edit-profile">编辑资料</button></div><div class="stats"><div><strong>132</strong><span>发布</span></div><div><strong>1.2万</strong><span>获赞</span></div><div><strong>356</strong><span>关注</span></div><div><strong>4821</strong><span>粉丝</span></div></div></div><div class="profileBody"><div class="card">${[['▣','我的发布',''],['☆','我的收藏','favorites'],['◔','浏览历史',''],['⚙︎','设置','settings']].map(x=>`<button class="menurow" ${x[2]?`data-nav="${x[2]}"`:''}><span style="color:var(--text3)">${x[0]}</span><span>${x[1]}</span><small>›</small></button>`).join('')}</div></div></div>${tabbar('profile')}`,
    favorites:()=>`${status()}${head('我的收藏')}<div class="body"><div class="chips">${['全部','成长','人生','情感','哲学','生活'].map((x,i)=>`<span class="topic ${!i?'active':''}">${x}</span>`).join('')}</div><div class="card">${[['山不过来，我就过去。','——《人生海海》',pic.mountain],['慢慢来，比较快。','—— 叔本华',pic.sea],['世界上只有一种真正的英雄主义，就是在认清生活的真相后依然热爱生活。','—— 罗曼·罗兰',pic.forest]].map(x=>`<div class="saved"><div class="thumb" style="background-image:url('${x[2]}')"></div><div><strong>${x[0]}</strong><small>${x[1]}<br># 人生 # 成长</small></div><div>⋯</div></div>`).join('')}</div></div>`,
    'edit-profile':()=>`${status()}${head('编辑资料')}<div class="body"><div class="card formCard"><div class="formAvatar"><div class="profileAvatar"><img src="${pic.person}"></div></div>${[['昵称','晚风'],['个性签名','在文字中，遇见更大的自己。'],['性别','选择性别　›'],['所在地','北京　›'],['个人主页','https://jianzi.app/u/wanfeng']].map((x,i)=>`<div class="inputGroup"><label>${x[0]}</label><div class="inputShell ${i===1?'multi':''}">${x[1]}</div></div>`).join('')}<button class="cta" style="width:100%">保存</button></div></div>`,
    settings:()=>`${status()}${head('系统设置')}<div class="body"><div class="card">${[['账号与安全',''],['通知设置',''],['外观模式','跟随系统'],['隐私设置',''],['清理缓存','12.6 MB'],['关于见字','v1.0.0'],['帮助与反馈',''],['退出登录','']].map((x,i)=>`<div class="settingrow" ${i===7?'style="color:#dd6262"':''}><div class="label"><span>${['⚙︎','◉','☰','◌','⌫','ⓘ','↗','⇥'][i]}</span><span>${x[0]}</span></div><span style="color:var(--text3)">${x[1]}</span><span style="color:var(--text3)">${i===7?'':'›'}</span></div>`).join('')}</div></div>`
  };

  const labels=[['home-reco','01 首页 · 推荐'],['home-follow','02 首页 · 关注'],['discover','03 发现页'],['search','04 搜索页'],['detail','05 详情页 · 评论'],['messages','06 消息页'],['message-detail','07 消息详情'],['publish','08 发布页'],['publish-success','09 发布成功'],['publish-fail','10 发布失败'],['profile','11 我的'],['favorites','12 我的收藏'],['edit-profile','13 编辑资料'],['settings','14 系统设置']];
  document.body.innerHTML=`<div id="app"><aside class="side"><h1>见字</h1><div class="brandline"></div><div class="slogan">每天刷 5 分钟，<br>吸收世界上最好的思想</div><div class="aside">好 的 文 字<br>让 平 凡 的 日 子<br>也 有 光</div></aside><main class="phone"><div class="viewport" id="viewport"><div class="island"></div><div class="screen" id="screen"></div></div></main><aside class="right"><div class="index"><h3>页面索引</h3>${labels.map(([k,t])=>`<button data-jump="${k}">${t}</button>`).join('')}</div><div class="token">设计基准：393 × 852<br>首页作为全局视觉母版<br>大圆角 · 轻阴影 · 低饱和绿 · 清晰层级</div></aside></div>`;
  const screen=document.querySelector('#screen');
  const stack=['home-reco'];
  function render(name,push=true){ if(!pages[name]) return; screen.innerHTML=pages[name](); if(push&&stack.at(-1)!==name)stack.push(name); document.querySelectorAll('[data-jump]').forEach(b=>b.classList.toggle('active',b.dataset.jump===name)); }
  function back(){ if(stack.length>1){stack.pop();render(stack.at(-1),false)} }
  document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){render(n.dataset.nav);return}const j=e.target.closest('[data-jump]');if(j){render(j.dataset.jump);return}if(e.target.closest('[data-back]'))back()});
  render('home-reco',false);
})();
